import { Component } from '@angular/core';
import { addIcons } from 'ionicons';
import {
  addCircleOutline,
  analyticsOutline,
  bagOutline,
  callOutline,
  cardOutline,
  checkmarkCircleOutline,
  chevronForwardOutline,
  createOutline,
  cubeOutline,
  gridOutline,
  heartOutline,
  helpCircleOutline,
  homeOutline,
  informationCircleOutline,
  leafOutline,
  locationOutline,
  logOutOutline,
  mailOutline,
  personCircleOutline,
  phonePortraitOutline,
  receiptOutline,
  removeCircleOutline,
  searchOutline,
  shieldCheckmarkOutline,
  sparklesOutline,
  speedometerOutline,
  star,
  storefrontOutline,
  timeOutline,
  trashOutline,
  walletOutline,
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  templateUrl: './app.html',
  standalone: false,
  styleUrl: './app.scss'
})
export class App {
  constructor() {
    addIcons({
      addCircleOutline,
      analyticsOutline,
      bagOutline,
      callOutline,
      cardOutline,
      checkmarkCircleOutline,
      chevronForwardOutline,
      createOutline,
      cubeOutline,
      gridOutline,
      heartOutline,
      helpCircleOutline,
      homeOutline,
      informationCircleOutline,
      leafOutline,
      locationOutline,
      logOutOutline,
      mailOutline,
      personCircleOutline,
      phonePortraitOutline,
      receiptOutline,
      removeCircleOutline,
      searchOutline,
      shieldCheckmarkOutline,
      sparklesOutline,
      speedometerOutline,
      star,
      storefrontOutline,
      timeOutline,
      trashOutline,
      walletOutline,
    });
  }
}
