import { Component } from '@angular/core';
import { addIcons } from 'ionicons';
import {
  addCircleOutline,
  alertCircleOutline,
  analyticsOutline,
  bagOutline,
  barChartOutline,
  callOutline,
  carOutline,
  cardOutline,
  checkmarkCircleOutline,
  chevronForwardOutline,
  chatboxEllipsesOutline,
  chatbubbleEllipsesOutline,
  clipboardOutline,
  closeCircleOutline,
  createOutline,
  cubeOutline,
  documentTextOutline,
  gridOutline,
  heartOutline,
  helpCircleOutline,
  homeOutline,
  informationCircleOutline,
  layersOutline,
  leafOutline,
  locationOutline,
  logOutOutline,
  mailOutline,
  optionsOutline,
  personCircleOutline,
  peopleOutline,
  phonePortraitOutline,
  pricetagOutline,
  receiptOutline,
  removeCircleOutline,
  saveOutline,
  searchOutline,
  settingsOutline,
  shieldCheckmarkOutline,
  sparklesOutline,
  speedometerOutline,
  star,
  storefrontOutline,
  timeOutline,
  trashOutline,
  walletOutline,
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  standalone: false,
  styleUrl: './app.component.scss',
})
export class AppComponent {
  constructor() {
    addIcons({
      addCircleOutline,
      alertCircleOutline,
      analyticsOutline,
      bagOutline,
      barChartOutline,
      callOutline,
      carOutline,
      cardOutline,
      checkmarkCircleOutline,
      chevronForwardOutline,
      chatboxEllipsesOutline,
      chatbubbleEllipsesOutline,
      clipboardOutline,
      closeCircleOutline,
      createOutline,
      cubeOutline,
      documentTextOutline,
      gridOutline,
      heartOutline,
      helpCircleOutline,
      homeOutline,
      informationCircleOutline,
      layersOutline,
      leafOutline,
      locationOutline,
      logOutOutline,
      mailOutline,
      optionsOutline,
      personCircleOutline,
      peopleOutline,
      phonePortraitOutline,
      pricetagOutline,
      receiptOutline,
      removeCircleOutline,
      saveOutline,
      searchOutline,
      settingsOutline,
      shieldCheckmarkOutline,
      sparklesOutline,
      speedometerOutline,
      star,
      storefrontOutline,
      timeOutline,
      trashOutline,
      walletOutline,
    });
  }
}
